AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for Alexa conversation persistence'

Resources:
  AlexaConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AlexaConversations
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: AlexaGenAI
        - Key: Environment
          Value: Production

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref AlexaConversationsTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt AlexaConversationsTable.Arn